language: python
python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - pip install flake8 coveralls unittest2
before_script:
  - mv gestorpsi/settings.py.TRAVIS gestorpsi/settings.py
  - mysqladmin create gpsi -u travis
  - python manage.py syncdb --noinput
  - python manage.py migrate
# command to run tests, e.g. python setup.py test
script:
  # - python manage.py test schedule
  - coverage run --source=gestorpsi manage.py test
  - flake8 gestorpsi

after_success:
    - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/971357a6ad46aa4c9940
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
