language: python
python:
  - "2.7"

install:
    - pip install -r requirements.txt
    - pip install coveralls unittest2
before_script:
  - mv gestorpsi/settings.py.TRAVIS gestorpsi/settings.py
  - python manage.py syncdb --noinput --migrate

script:
  - ./run_tests.sh

after_script:
    - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/87309c799eae69dfdbbc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
